apiVersion: apps/v1
kind: Deployment
metadata:
  name: jdk-deployment
spec:
  selector:
    matchLabels:
      app: jdk
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: jdk
    spec:
      containers:
      - name: jdk
        image: cgr.dev/manojgupta.in/jdk-non-unique:openjdk-8
        ports:
        - containerPort: 80
